import LanguageLoadingOverlayClient from "@/components/ui/language-loading-overlay-client";
import { LanguageProvider } from "@/contexts/language-context";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Figtree, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxLayout from "./ReduxLayout";

const figtree = Figtree({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={cn("font-sans", figtree.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <ReduxLayout>
            {children}
          </ReduxLayout>
          <LanguageLoadingOverlayClient />
        </LanguageProvider>
      </body>
    </html>
  );
}
